[secret]
owner = "REPLACE THIS WITH YOUR NAME"
login = "INSERT THE BOTS NAME"
oauth = "INSERT THE BOTS OAUTH KEY"
client_id = "INSERT THE BOTS ID"
client_secret = "INSERT THE BOTS SECRET"
channel_name = "INSERT THE NAME OF THE CHANNEL YOU WANT THE BOT TO BE IN"
openweather_oauth = "INSERT YOUR OPENWEATHERMAP OAUTH KEY HERE"

